#!/bin/bash -e

commit_msg=$(cat $1)
if [[ $commit_msg != [* ]]; then
  branch=$(git symbolic-ref HEAD|sed s#refs/heads/##)
  branch=$(echo "$branch" | sed -e 's$/$\\/$g')
  sed -i -e "1s/^/[${branch}] /" "$1"
fi
